spring:
  application:
    name: t1-java-demo
  datasource:
    url: "jdbc:postgresql://localhost:5432/t1_java_db"
    username: "postgres"
    password: "postgres"
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml

server:
  port: 8090

logging:
  level:
    ROOT: INFO
    ru.t1.java.demo.controller.ClientController: DEBUG

t1:
  scan-path: ru.t1.java.demo
  kafka:
    enabled: ${TRACK_KAFKA_LOG_ENABLED:true}
    bootstrap:
      server: ${KAFKA_SERVER:localhost:9092}
    consumer:
      group-id: t1_demo
      max-poll-records: 10
    producer:
      enable: true
    topic:
      client-registration: t1_demo_client_registration
      client-id-registered: t1_demo_client_registered
      client-transactions: t1_demo_client_transactions

      data-source-errors: t1_demo_data_source_error
      methods-metric: t1_demo_metrics
      account-registration: t1_demo_accounts
      transaction-registration: t1_demo_transactions

      header:
        data-source-errors-header: DATA_SOURCE
        methods-metric-header: METRICS

    listener:
      poll-timeout: 1000

track:
  errors-to-track: JsonParseException, IOException
  method-execution-time-limit-ms: 500


  db:
    enabled: false
  time-limit-exceed: 1000
  log-level: DEBUG
